#pragma once

#include <U8g2lib.h>

// This is a shortened u8g2 ProFont for ESFloppy's 128x64 OLED
// Since I'm not artistic in the slightest, I had Claude generate this for me
// Everything that follows this comment was generated by it
//
// Derived from u8g2_font_profont11_tf, which is 6px wide but has a 10-row ink band
// (7-row capitals plus 2-row descenders plus the taller parentheses), so only four
// menu rows fit on the panel. This version keeps ProFont's exact 6px monospace cell
// and stroke weight but shortens the band to 7 rows: 6-row capitals with descenders
// dropping into a single row below the baseline. At an 8px pitch that leaves one
// blank separator row and fits eight rows on the display.
//
// 71 of the 95 glyphs were shortened losslessly, by deleting one row of an adjacent
// identical pair (a stem or a straight side), which leaves the letterform untouched.
// The remaining 23 - # $ % & * , 0 2 3 4 ; < > ? @ K S Z ^ _ ` g y - had no repeated
// row to spare and were redrawn by hand.
//
// Metrics: monospace, advance 6, ascent 6, descent 1, band 7, ASCII 32-126.

extern const uint8_t u8g2_font_profont6_tr[884] U8G2_FONT_SECTION("u8g2_font_profont6_tr");
